spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false  #服务注册，false标识不将自己注册到Eureka服务中
    fetch-registry: false  #服务发现，false表示自己不从Eureka服务中获取注册信息
    service-url: #Eureka客户端与Eureka服务器的交互地址，集群版配置对方的地址(多台用逗号分隔），单机版配置自己（如果不配置则默认本机8761端口）
      #单机版
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://127.0.0.1:6001/eureka/
  server:
    enable-self-preservation: false  #禁用自我保护机制

---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: microservice-config-eureka

eureka:
  instance:
    hostname: eureka6001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false  #服务注册，false标识不将自己注册到Eureka服务中
    fetch-registry: false  #服务发现，false表示自己不从Eureka服务中获取注册信息
    service-url: #Eureka客户端与Eureka服务器的交互地址，集群版配置对方的地址(多台用逗号分隔），单机版配置自己（如果不配置则默认本机8761端口）
      #单机版
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://127.0.0.1:6001/eureka/
  server:
    enable-self-preservation: true  #开启自我保护机制